# Site settings
title: '{aroundProgramming}'
title_small: '{dp}'
email: konjoot@gmail.com
description: > #
  Возможно здесь должно быть описание, но зачем?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: konjoot
github_username:  konjoot
author: Максимов Сергей

# Build settings
markdown: kramdown
